name: Execute Make Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-make:
    runs-on: ubuntu-latest
    timeout-minutes: 10


    steps:
    # Step 1: Check out the repository
    - name: Check out repository
      uses: actions/checkout@v3

    # Step 2: Install dependencies (using make install)
    - name: Install dependencies
      run: make install

    # Step 3: Execute the notebook (using make run)
    - name: Execute notebook
      run: make run